---
- name: Diagnostic Ansible AWX
  hosts: localhost
  gather_facts: false
  become: true
  become_user: "dhia"
  vars:
    file_loc: /home/dhia/Desktop/jinja2test/survey-template.conf
    output_loc: /home/dhia/Desktop/jinja2test/survey-result.conf
  vars_files:
      - vars.yml

  tasks:
    - name: Vérifier la présence des variables
      debug:
        msg: "serv_name={{ serv_name }}, option1={{ option1 }}, option2={{ option2 }}"

    - name: Copier le template
      template:
        src: survey-template.conf.j2
        dest: "{{ file_loc }}"

    - name: Lire le contenu du fichier généré
      slurp:
        src: "{{ file_loc }}"
      register: slurped_file

    - name: Enregistrer le contenu dans un autre fichier
      copy:
        content: "{{ slurped_file.content | b64decode }}"
        dest: "{{ output_loc }}"

    - name: Afficher ce qu'on a écrit dans output.txt
      debug:
        msg: "Contenu écrit dans {{ output_loc }}"
