---
- name: demonstrate using surveys with templates
  hosts: localhost
  gather_facts: false
  become: true
  vars:
    file_loc: /home/dhia/Desktop/jinja2test/survey-template.conf
    result_loc: /home/dhia/Desktop/jinja2test/survey-result.conf

  tasks:
    - name: Créer le dossier si inexistant
      ansible.builtin.file:
        path: /home/dhia/Desktop/jinja2test
        state: directory
        mode: '0755'

    - name: call the template with our survey info
      template:
        src: survey-template.conf.j2
        dest: "{{ file_loc }}"
        force: yes

    - name: set file contents to variable
      set_fact:
        file_con: "{{ lookup('file', file_loc) }}"

    - name: debug file to screen
      debug:
        var: file_con

    - name: Sauvegarder le résultat dans un fichier de résultat
      copy:
        content: "{{ file_con }}"
        dest: "{{ result_loc }}"

